services:
  link-steward:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: link-steward
    ports:
      - "3088:80"
    volumes:
      - ${LINK_STEWARD_HOST_DATA_DIR:-./data}:/var/www/html/data
    restart: unless-stopped
